spring:
  application.name: gateway-service
  profiles.active: ${ENV:local}

#GATEWAY
zuul.routes:
  subscriptions:
    path: /subscription/**
    serviceId: subscription-service
    strip-prefix: false
ribbon.eureka.enabled: false