version: '3'

services:
  subscription-service:
    image: borjasanba/adidas-subscription-service
    ports:
      - "8081:8081"
    hostname: subscription
    environment:
      - ENV=docker-compose
    depends_on:
      - mysql
      - kafka
    links:
      - kafka:kafka

  mysql:
    image: mysql:5.7.22
    container_name: subscriptions-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ADIDAS

  kafka:
    image: wurstmeister/kafka
    container_name: subscriptions-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=adidas_subscription:8:1,dlq_adidas_mail:8:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper