server.port: 8082
management.endpoint.health.show-details: always
logging.level.com.adidas.challenge: DEBUG

#KAFKA
spring.cloud:
  stream.kafka.streams.binder.brokers: localhost:9092

#EMAIL
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: username
  password: password
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true
